enum AppSection {
  dashboard,
  taxation,
  taxationList,
  taxationTaxpayers,
  taxationNomenclature,
  ordonnancement,
  apurement,
  recouvrement,
  communes,
  rapports,
  alertes,
  utilisateurs,
  utilisateursAgents,
  utilisateursContribuables,
  parametres,
}
